  address: 0.0.0.0 # set to '*' to bind to all interfaces (0.0.0.0 ALLOWS the outside world to hit it. localhost only allows access from that box)
  # port where Trinidad is running
  port: 3001
  # specify with `trinidad -e production`
  environment: '<%= ENV['RAILS_ENV'].nil? ? 'development' : ENV['RAILS_ENV']%>'
  http: # HTTP connector setup
    acceptCount: 100
    maxThreads: 200
    maxKeepAliveRequests: 100

    # @see https://github.com/trinidad/trinidad/wiki/HTTP-Connector
<% unless ENV['SSL_PORT'].nil? %>
  ssl: # SSL configuration
    port: <%= "#{ENV['SSL_PORT']}"%>
    #@see https://github.com/trinidad/trinidad/wiki/Secure-Socket-Layer
    #keystore: c:\temp$trin/etc/trinidad/default.keystore
    #keystorePass: somepassword
<% end %>
  #ajp: # AJP configuration
    #port: 8009
    # @see https://github.com/trinidad/trinidad/wiki/AJP-Configuration
  #apps_base: # directory where several applications are located
  #
  # Begin: Configuration options that can be overrided per web-application
  #
  threadsafe: false # overrides config.threadsafe! detection
  jruby_min_runtimes: 1 # min number of JRuby runtimes to use
  jruby_max_runtimes: 1 # max number of JRuby runtimes to use
  #jruby_compat_version: 1.9 # or 1.8 by default uses the same as trinidad is running
  context_path: / # default context path
  root_dir: "." # system path where the application is located, by default is PWD
  #rackup: config.ru # rackup script if you are running a (non-Rails) Rack application
  public: public # system path (relative to root) where your public files are located
  # If you do not put a web-server in front of Trinidad you might tune asset caching :
  #public:
  #  root: public # same as the above "public: public" setting
  #  aliases: # allows to "link" other directories into the public root e.g. :
  #    /home: /var/local/www
  #  cached: true # enable (in-memory) asset caching on for env != 'development'
  #  cache_ttl: 5000 # cache TTL in millis (might want to increase this)
  #  cache_max_size: 10240 # the maximum cache size in kB
  #  cache_object_max_size: 512 # max size for a cached object (asset) in kB
  java_lib: lib/java # directory where libraries packed as jars can be found
  java_classes: lib/java/classes # directory where compiled java classes can be found
  default_web_xml: config/trinidad-web.xml # if you are using a custom web.xml
  reload_strategy: default # alternatively you might use "rolling"
  monitor: <%= RbConfig::CONFIG["host_os"].eql?('mswin32') ? 'c:/temp/restart.txt' : '/tmp/restart.txt' %>
  #monitor: /tmp/restart.txt

  #
  # End: Configuration options that can be overrided per web-application
  #
  extensions: # if you are using any Trinidad extension
    #daemon: # sample daemon extension
      #pid_file: # pid file
      #jvm_args: # additional arguments for the thread that runs the daemon
  #
#  web_apps: # if running more than one application or using web apps extensions
#    default: # by default the name is used as the context path, 'default' means the root path '/'
#       # here you can override any already configured options or add new ones e.g. :
#       extensions:
#         sandbox:
#          #context_path: management
#          username: tomcat
#          password: tomcat
#          mysql_dbpool:
#            jndi: 'jdbc/BarDB'
#            url: 'localhost:3306/bar'
#            username: root
#            password: pass
#            maxActive:  100 # maximum number of connections managed by the pool
#            initialSize: 10 # initial number of connections created in the pool
#            maxWait:  10000 # ms the pool waits for a connection to be returned
#    # configuring another application :
#    foo_app:
#      context_path: /foo # this will be the path rather than '/foo_app'
#      web_app_dir: /var/www/foo_app # system path where this application is located